### ISSUE TITLE
ReadTimeoutException on parallel access

### ISSUE THREAD

**Issue by chrloch** [eu-federation-gateway-service/efgs-federation-gateway#107]
Executed a simulation with 2 countries against ACC environment. 
Ratio upload:download was set to 1:20 (with randomized call order)
3 out of 8 uploads that were triggered in the simulation failed with a ReadTimeoutException registered by the CWA Simulator

Time of simulation was 2020-09-07 from 16:30 to 17:00 CET 

[efgs-simulator.log](https://github.com/eu-federation-gateway-service/efgs-federation-gateway/files/5183864/efgs-simulator.log)

**Comment by f11h** [comment]
Today the latest version was deployed. Can you please retest this?

this bug relates to #73

**Comment by f11h** [comment]
Isolation level needs to be set by DIGIT to get reliable results.

**Comment by chrloch** [comment]
What are the correct settings for the isolation level?

**Comment by f11h** [comment]
Isolation level needs to be REPEATABLE_READ

**Comment by chrloch** [comment]
Isolation level set by DIGIT, repeated test with 2 countries and higher timeout value in simulator. 
Error reproduced:

timestamp=2020-09-09T11:58:48.267Z, level=INFO, hostname=EFGS-SIM-BE, pid=52751, trace=, span=, thread=http-nio-8091-exec-9, class=e.i.f.service.EfgsSimulatorService, message="Start calling upload"
timestamp=2020-09-09T11:58:48.269Z, level=DEBUG, hostname=EFGS-SIM-BE, pid=52751, trace=, span=, thread=reactor-http-epoll-2, class=org.springframework.web.HttpLogging, message="[59fafc2b] Writing 19872 bytes"
timestamp=2020-09-09T12:01:41.348Z, level=WARN, hostname=EFGS-SIM-BE, pid=52751, trace=, span=, thread=reactor-http-epoll-3, class=r.netty.http.client.HttpClientConnect, message="[id: 0xb869a53d, L:/10.0.0.6:54132 - R:acc-efgs-ws.tech.ec.europa.eu/147.67.34.67:443] The connection observed an error"
io.netty.handler.timeout.ReadTimeoutException: null
timestamp=2020-09-09T12:01:41.356Z, level=ERROR, hostname=EFGS-SIM-BE, pid=52751, trace=, span=, thread=http-nio-8091-exec-8, class=o.a.c.c.C.[.[.[/].[dispatcherServlet], message="Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is io.netty.handler.timeout.ReadTimeoutException] with root cause"
io.netty.handler.timeout.ReadTimeoutException: null

**Comment by chrloch** [comment]
Retest after deployment of  https://github.com/eu-federation-gateway-service/efgs-federation-gateway/commit/de49b06515cee342cb60629137cc79a63cb2b41a

Reproduced the error

**Comment by chrloch** [comment]
Retest after setting of isolation level on DB at 2020-09-11 12:00-12:30 UTC (reference for log timestamps)

Reproduced the error
[20200911T140257_EFGS_2C_JSON.zip](https://github.com/eu-federation-gateway-service/efgs-federation-gateway/files/5211043/20200911T140257_EFGS_2C_JSON.zip)

**Comment by chrloch** [comment]
Failed requests cannot be found in Logs (Splunk or DynaTrace). No exceptions can be linked to the failed requests. 

Performed several tests to reproduce the error today on ACC environment: 

9 uploads + 170 downloads in 30 minutes --> 4 failed uploads
200 uploads in few seconds --> 1 failed upload 
uploads (manual abort) with 1s pause between --> 2 failed uploads after 2 minutes 
=> Conclusion: The issue is **not related to the load**. Sporadically, upload requests seem to not reach the tomcat servers.

**Comment by alstiefel** [comment]
Updating SIMU to add message ids to upload messages, to allow better searching for messages in wireshark logs

**Comment by chrloch** [comment]
Stress Test on 17.09.2020 used same hosts for uploads and downloads --> reduced timeouts dramatically.
Issue seems to be stronger on hosts only sending POST with large body and no GET, also pauses between requests cause more errors than when many requests come in short time

**Comment by chrloch** [comment]
Tests on 21.09.2020 could not reproduce error
Repeated test with 2 countries in setup which error was first discovered.
Also 4 hours test with curl triggered simulator did not reproduce error either.

**Comment by chrloch** [comment]
Changes that have led to the solution of  the bug cannot be determined
