### ISSUE TITLE
Provide Runbook for Certificate Gov Process focusing on the offline process

### ISSUE THREAD

**Issue by paszimme** [eu-federation-gateway-service/efgs-federation-gateway#109]
- create run book
- describe process
    - howto onboard NB certificates
    - howto create EFGS cerficates and how to insert them into keystore
    - create signature
    - how to move in db
- provide Tools for on boarding
- initial creation of keystores and import of keys/certs

Scope for dev team is DEV/TEST
Ops will use the scripts for ACC/PRD

**Comment by alstiefel** [comment]
increased scope:
initial creation of keystores and import of keys/certs

**Comment by alstiefel** [comment]
done see https://github.com/eu-federation-gateway-service/efgs-admin/blob/master/docs/certs_key_handling.md
