### ISSUE TITLE
Rest API: Download: Diagnosis keys newer then download date are not downloaded

### ISSUE THREAD

**Issue by FWeissenseelTSystems** [eu-federation-gateway-service/efgs-federation-gateway#112]
## Describe the bug

When you set in rest API "download" a date in the past, diagnosis keys newer then the set date are not downloaded. Only the diagnosis keys of the set date are downloaded.

## Expected behaviour

When you download data for date X, all diagnosis keys of date X and newer should be downloaded.

See document: 20201408_EU_Interop_Architecture_v1.3_draft.pdf (chapter: download interface):
    "diagnosis keys newer than {date} will be downloaded

## Steps to reproduce the issue

Example:
01.09:  100 diagnosis keys uploaded by other countries
02.09:  500 diagnosis keys uploaded by other countries
03.09:  200 diagnosis keys uploaded by other countries

When you download data for 02.09, only the 500 keys are downloaded. 
When you download data for 02.09, 500+200 = 700 keys should be downloaded.

**Comment by alstiefel** [comment]
Pls review, whether this was already fixed as side effect of other fix

**Comment by f11h** [comment]
eu.interop.federationgateway.service.DiagnosisKeyBatchService#getFirstBatchTagOfTheDay
--> remove end variable

eu/interop/federationgateway/controller/DownloadController.java:162
--> change check to proof that batch date is gte to requested date

eu.interop.federationgateway.service.DiagnosisKeyBatchService#getFirstBatchTagOfTheDay
--> remove end variable (just get the last entity with batchLink is null
--> if no entity is present generate the first batchTag

eu/interop/federationgateway/service/TransactionalDiagnosisKeyBatchService.java:112
--> move the setBatchLink call outside of the if-block so it will be always set.

**Comment by alstiefel** [comment]
Our first analysis shows conflicting interpretation of the specification
1. "4.2.9 Document Batch Tag" -->   it’s used to “navigate” within the day
1. "5.3.1" Download API spec mentions  --> diagnosis keys newer than {date} will be downloaded

The proposal to be verified would be:

For /download/date/{date}, if no batchtag is provided, find the first batch not older than date
For /download/date/{date}, if batchtag is provided, find the first batch not older than date having the batchtag

**Comment by ryanbnl** [comment]
When first connecting to the EFGS, will this pseudo-ish code provide me with all available keysets?

```
date = today - 14-days
batchTag = null
while(batch = efgs.download(date, batchTag) != null)
    (nextDate, nextBatchTag) = process(batch)
    date = nextDate
    batchTag = nextBatchTag
    
```

How would this work when the date is `today` and you're polling every, say, hour, to see if there are new batches? You can't link to a non-existing batch the API doesn't accept a time..
