### ISSUE TITLE
detailed documentation for integration or just debug mode for endpoints.

### ISSUE THREAD

**Issue by flamaniac** [eu-federation-gateway-service/efgs-federation-gateway#121]
## Current Implementation
The Debug mode would be nice. I am trying to upload keys but getting 500 without any message what is wrong.
Are you realy using protobuffer version 1? (the latest is v3 ) or it is just Swagger wrong?

## Suggested Enhancement

Debug messages for upload keys method or better, more detailed documentation for that. 

## Expected Benefits
Less time to intagreate.

**Comment by daniel-eder** [comment]
@flamaniac Thank you for the suggestion, our developers will discuss if a debug mode is viable and we'll get back to you!

**Comment by daniel-eder** [comment]
@flamaniac A debug mode is currently not in the specifications (or time plan) by the EU, therefore we cannot implement it at this point. 

Regarding your specific issue and the (lack) of HTTP error messages: 
- 4xx responses should come with error messages 
- 5xx responses are server errors, they can be seen in the log 
- Any deviation from that behaviour is likely a bug - please create an issue specific to the problem and we will look into it.

I will close this issue for now, but please feel free to comment or reopen it if anything remains unclear.

Thank you!

**Comment by flamaniac** [comment]
Yes. I have rebuild gateway project by maven and now I get a proper http code.
