### ISSUE TITLE
Duplicate attribute names in logs

### ISSUE THREAD

**Issue by ctsung** [eu-federation-gateway-service/efgs-federation-gateway#127]
## Current Implementation

'hostname' is used twice: Log Message Structure and Callback URL verification.

## Suggested Enhancement

'hostname' in Log Message Structure
'callbackHostname' in Callback URL verification

## Expected Benefits

For CDC, the change would reduce the difficulties when parsing the logs.

**Comment by daniel-eder** [comment]
Thank you for letting us know! Our developers will review if and when we can implement it and get back to you.
If you have a clear idea where this needs to be changed, you can provide a PR if possible.

**Comment by daniel-eder** [comment]
@ctsung We just discussed this, there are currently no developer capacities to implement this change, however, if you provide a PR are happy to accept the suggested improvement.

**Comment by ascheibal** [comment]
Hi @ctsung , your PR is merged. Thank you for contribution.
