### ISSUE TITLE
Provide a profile for local test

### ISSUE THREAD

**Issue by fredrb** [eu-federation-gateway-service/efgs-federation-gateway#133]
## Current Implementation

When running EFGS locally, there is a huge amount of set-up needed for the authentication. Creating TLS/Signing certificates and generating the proper thumbprints/signatures for each. This is needed for a complete end-to-end test (like validating signatures) but for quick, local development and automated testing that's really cumbersome to set up. 

## Suggested Enhancement

Create a new profile (e.g. `no-certificate` or `skip-auth`) that will skip certificate validation and signature validation. This will allow any developer to post upload batches and download batches without having to go through the whole setup. 

We can still have a "fake" TLS certificate entry in the DB that would allow EFGS to verify which country is sending the request. As long as the client sends the proper fake thumbprint and CN on the request header. 

## Expected Benefits

- Easier to setup local environment, there is no need to generate test keys and provision them in the DB
- Easier to create environment for automated testing, as simply spinning up a container and a DB with a fake TLS certificate is sufficient 
- Easier to test integration between National Back-Ends and EFGS

**Comment by daniel-eder** [comment]
Thank you for your suggestion! We'll review it and get back to you if and how we can proceed.

**Comment by alstiefel** [comment]
Thank you for your input.

As we learn from teams trying to integrate with EFGS, the dealing with all the certificates is a major challenge and it slows down development. 

To ease local development I would propose other options which all address the complexity rooted in the certificate by providing db content, keystores for EFGS and keystores for the local client to speed up readiness for developers.

I see significant disadvantages of having a code path disabling security procedures. Having a property disabling security verification increases the attack surface and the risk of security bugs.

**Comment by fredrb** [comment]
> To ease local development I would propose other options which all address the complexity rooted in the certificate by providing db content, keystores for EFGS and keystores for the local client to speed up readiness for developers.

I think that's a great idea. I understand that adding a code path that skips authentication checks can be a major security risk. But if there is a way to start EFGS with dummy certificates and private keys that we can use for TLS and batch signing that would be great. 

From CWA side we could simply point our configuration to these dummy keys provided in EFGS repository for local testing. Perhaps providing enough key-pairs to simulate two countries would be the way to go. Because we could test upload with one and download with another.
