### ISSUE TITLE
Proto v2 vs. Proto v3 Upload Submission

### ISSUE THREAD

**Issue by SchulzeStTSI** [eu-federation-gateway-service/efgs-federation-gateway#136]
Hello:) 

If proto v2 is used for the content body during the upload, there is not hint or exception that v3 is expected by the server. The user gets "invalid signature" which leads to a lot of confusion, because the server interprets it as proto v3. It seems that some bytes are inserted or removed during this conversion, but from outside it looks like an wrong signature calculation, actually it's the transport. 

Suggestion to solve: 

a) Check if used format is proto v2, if yes return an content type exception with the hint that v3 has to be used and stop the processing
b) Insert a Log Entry that this was tried

Thanks!

**Comment by alstiefel** [comment]
From DEV perspective this is a request for an enhancement. We will move this into a post 1.0.0 scope
