### ISSUE TITLE
Signature Verification uses not the correct Certificate Algorithm

### ISSUE THREAD

**Issue by SchulzeS** [eu-federation-gateway-service/efgs-federation-gateway#147]
<h2>Description</h2>

If some one creates the certificates according the appendix: 

https://github.com/eu-federation-gateway-service/efgs-federation-gateway/blob/master/docs/software-design-federation-gateway-service.md#appendix-a

...the certificate has an ECC Signature not RSA. 

The code line: 

      Signature verifier = Signature.getInstance("SHA256with" + publicKey.getAlgorithm());

assumes that SHA256withECC exists. Actually it's ECDSA. This works just with RSA generated certificates.

<h2> Possible Fix</h2>

Currently the Certificate class is used. This class provides not the full information. The class X509Certificate should be used to get the correct singaturealgorithm via getSigAlgName() or better: getSigAlgOID(). 
  
`Signature verifier = Signature.getInstance(certificate.getSigAlgName());`
`PublicKey = certificate.getPublicKey();...`

**Comment by alstiefel** [comment]
Pls comment

**Comment by f11h** [comment]
This problem only occurs when efgs is self hosted and the TrustAnchor certificate is EC signed.

All of our deployments are using RSA/SHA256 certificates so we may have a look on this in future, but it is not critically.

The usage of EC certificates for uploading keys was tested here: #92

**Comment by qLb** [comment]
Critical, maybe not - but it leads people following your reference docs into rabbit holes.
I suggest either a important note inside your docs or a proper fix inside the source code.
