### ISSUE TITLE
Batch download request yields different response codes for empty responses

### ISSUE THREAD

**Issue by mibrasap** [eu-federation-gateway-service/efgs-federation-gateway#150]
## Describe the bug

When downloading keys, the gateway behaves in two different ways when there are no keys available.
The request to download keys from the past, e.g. `...diagnosiskeys/download/2020-08-27` returns a 404 Not Found, which meets the expectations.
The same request for the current day `...diagnosiskeys/download/2020-09-17` instead returns a 200 OK with empty response body.

## Expected behaviour

Return the same response code 404 Not Found also for the current date, as it is the case for dates in the past.

## Steps to reproduce the issue

1. Send a GET request to the gateway URL `...diagnosiskeys/download/2020-09-10` for a date where no keys exist (depending on your gateway instance setup and data). You will see a response with response code 404 Not Found
2. Send a GET request to the gateway URL `...diagnosiskeys/download/<current-date>`. You will see a response with response code 200 Ok, but the response body is empty.

**Comment by daniel-eder** [comment]
Hi @mibrasap, thanks for the bug report. Our developers will discuss this and compare it to the specification documents and we'll get back to you!

**Comment by f11h** [comment]
Hi @mibrasap ,

you are not getting a non 2xx response because the batch you have tried to download (and possibly more) actually exists for this date. But it contains only keys uploaded by your own country. EFGS will not deliver you any key uploaded from your own country so it responds with an empty array.
