### ISSUE TITLE
Really disable swagger

### ISSUE THREAD

**Issue by alstiefel** [eu-federation-gateway-service/efgs-federation-gateway#154]
Swagger

**Comment by f11h** [comment]
https://stackoverflow.com/questions/37794571/how-do-you-turn-off-swagger-ui-in-production#:~:text=6%20Answers&text=Put%20your%20swagger%20configuration%20into,context%20only%20in%20certain%20profiles.&text=You%20can%20than%20define%20profile,profiles.
