### ISSUE TITLE
Undocumented but implemented log messages

### ISSUE THREAD

**Issue by ctsung** [eu-federation-gateway-service/efgs-federation-gateway#171]
## Feature description

Documents for logs that are already implemented in the source code but not yet documented

## Problem and motivation

Some logs are implemented and found in the source code, but they are not documented. CDC has rules based on interesting ones so that potential errors can be monitored as well. It would be great that they are kept if they don't disobey data privacy regulations.

## Is this something you're interested in working on

No.

**Comment by f11h** [comment]
Add Log Message for Cleanup to Documentation

**Comment by joerg-oppermann-tsi** [comment]
fixed with https://github.com/eu-federation-gateway-service/efgs-federation-gateway/issues/189
