### ISSUE TITLE
Documented but not yet implemented log messages

### ISSUE THREAD

**Issue by ctsung** [eu-federation-gateway-service/efgs-federation-gateway#172]
## Your Question

* Source File: https://github.com/eu-federation-gateway-service/efgs-federation-gateway/blob/master/docs/software-design-federation-gateway-service.md
* Line(s): Starting from 102
* Question:
The following log messages can't be found in the source code:
```
'batchtag already exists' (Is this 'batchtTag already exists' actually?)
'Could not find a Callback Certificate for host'
'Could not find callback certificate.'
'Found Callback Certificate, but it is revoked'
'wrong signature'
```

Will they still be implemented? Or are they somehow rephrased in the source code?

Thanks in advance for looking into this.

**Comment by dfischer-tech** [comment]
Hi @ctsung, thx for asking
the first message exists and is actually 'batchtag already exists'. 
[UploadController - line 156 - log.error("**batchTag already exists**")]
The other messages 2nd - 5th are **no** longer there.
The the document will be adapted.
greetings
