### ISSUE TITLE
Integrate OWASP security check into build

### ISSUE THREAD

**Issue by alstiefel** [eu-federation-gateway-service/efgs-federation-gateway#191]
via maven ... details Alex

**Comment by UWilhelm** [comment]
Nach meinem Verstaendnis geht es hier um den OWASP Dependency-Check:
https://owasp.org/www-project-dependency-check/
Dies zahlt auch explizit auf den Security Issue 12 (https://github.com/eu-federation-gateway-service/efgs-security/issues/12) ( Outdated Vulnerable Components 12) ein.
