### ISSUE TITLE
Add count for real & fake/dummy keys to packages

### ISSUE THREAD

**Issue by tklingbeil** [eu-federation-gateway-service/efgs-federation-gateway#197]
## Feature description

Add the information to each key bundle, how many of the contained keys are real and how many have been added as padding (i.e. fake/dummy keys) for data privacy reasons.

## Problem and motivation

The amount of keys contained in a package might provide information about how many users have submitted a test result. The use of fake/dummy keys as padding for the package requires information about the amount of added keys to make a proper estimation.

## Is this something you're interested in working on

Yes

**Comment by iCesofT** [comment]
IMHO EFGS should not persist fake/dummy keys. If you do so, all countries would download those keys.
