### ISSUE TITLE
daysSinceOnsetOfSymptoms is not set in downloaded data

### ISSUE THREAD

**Issue by alstiefel** [eu-federation-gateway-service/efgs-federation-gateway#207]
details will be provided
OTC E2E EFGS

**Comment by EvgeniiSkrebtcov** [comment]
**EFGS Environment:** 
https://ecs-80-158-6-221.reverse.open-telekom-cloud.com/efgs/

**Example:** 
date 2020-10-09 and batchTag 20201009-27

**Comments:**
300 of 4000 keys in the batch cant be processed because: " Days since onset of symptoms is missing"

**Comment by BugBuster1701** [comment]
efgs Log files for analysis.
[tomcat3-efgs.log](https://github.com/eu-federation-gateway-service/efgs-federation-gateway/files/5355141/tomcat3-efgs.log)
[tomcat2-efgs.log](https://github.com/eu-federation-gateway-service/efgs-federation-gateway/files/5355142/tomcat2-efgs.log)
[tomcat1-efgs.log](https://github.com/eu-federation-gateway-service/efgs-federation-gateway/files/5355143/tomcat1-efgs.log)

**Comment by dfischer-tech** [comment]
The first impression so far, the upload and download could be traced in the log file. No error message in the EFGS process. Can someone provide us the upload key data?

**Comment by BugBuster1701** [comment]
the data looks ok
select payload_days_since_onset_of_symptoms,count(*) from diagnosiskey where batch_tag='20201009-27' group by 1;

```
+--------------------------------------+----------+
| payload_days_since_onset_of_symptoms | count(*) |
+--------------------------------------+----------+
| /j1IwNbRM1hoYq4ZotlakQ==             |      320 |
| 31Q8ZS1b0eKzi0cunTb9pg==             |      300 |
| 60jcqXD2NRStvvhNO/LCtA==             |      300 |
| 6n90uqjhky4GeJhdGrckyA==             |      300 |
| HetGpgrRfce2KOcMr7fMRw==             |      320 |
| hV7ulwnqKonxsMfl/Zw7iQ==             |      300 |
| JXr0kfKaNFzulHZuZl0j9Q==             |      312 |
| kxy4wI6PoGY6ThmVnYlqGQ==             |      290 |
| MxBZy1S0YFb6rcmDaPU+zw==             |      320 |
| SQeJ/bfB/e6EulF/uhgLBg==             |      320 |
| Tyhnn+ARl71P9FcfKetokA==             |      320 |
| Xc5Ju04GzKJUIIXyErPXwg==             |      318 |
| Xhrm5woYEwFbM08CUI85ug==             |      280 |
+--------------------------------------+----------+

```

**Comment by mschulte-tsi** [comment]
Decoding the 300er we cant decrypt one of the group
...
31Q8ZS1b0eKzi0cunTb9pg==  MA==  No printable characters found
60jcqXD2NRStvvhNO/LCtA==  Mg==  2
6n90uqjhky4GeJhdGrckyA==  Mw==  3
hV7ulwnqKonxsMfl/Zw7iQ==  MQ==  1
...

**Comment by EvgeniiSkrebtcov** [comment]
> 31Q8ZS1b0eKzi0cunTb9pg== MA== No printable characters found

does not look like Int ...

**Comment by alstiefel** [comment]
The related uploader batch tag, related to the broken int
+--------------------------------+
| uploader_information_batch_tag |
+--------------------------------+
| 2020-10-9-4CGNDA==-0 |
+--------------------------------+

**Comment by mschulte-tsi** [comment]
The assumtion that we have corrupted data, is not longer standing 

31Q8ZS1b0eKzi0cunTb9pg== MA== No printable characters found
Decodes with anoter Base64 Decoder to 0

**Comment by dfischer-tech** [comment]
I imported the database dumb locally (😳 WOW 110637 Keys...)
I tested the download for (doc batch=**20201009-1**, uploaderbatch=**2020-10-9-4CGNDA==-0**)
expectet 4000 Keys - DB check by: 
`select batch_tag, uploader_information_batch_tag, payload_days_since_onset_of_symptoms, count(*) from fg.diagnosiskey where uploader_information_batch_tag='2020-10-9-4CGNDA==-0' group by 3;`

| batch_tag  | uploader_information_batch_tag | payload_days_since_onset_of_symptoms | count(*) |   |
|------------|--------------------------------|--------------------------------------|----------|---|
| 20201009-1 | 2020-10-9-4CGNDA==-0           | /j1IwNbRM1hoYq4ZotlakQ==             | 320      |   |
| 20201009-1 | 2020-10-9-4CGNDA==-0           | 31Q8ZS1b0eKzi0cunTb9pg==             | 300      |   |
| 20201009-1 | 2020-10-9-4CGNDA==-0           | 60jcqXD2NRStvvhNO/LCtA==             | 300      |   |
| 20201009-1 | 2020-10-9-4CGNDA==-0           | 6n90uqjhky4GeJhdGrckyA==             | 300      |   |
| 20201009-1 | 2020-10-9-4CGNDA==-0           | HetGpgrRfce2KOcMr7fMRw==             | 300      |   |
| 20201009-1 | 2020-10-9-4CGNDA==-0           | hV7ulwnqKonxsMfl/Zw7iQ==             | 300      |   |
| 20201009-1 | 2020-10-9-4CGNDA==-0           | JXr0kfKaNFzulHZuZl0j9Q==             | 334      |   |
| 20201009-1 | 2020-10-9-4CGNDA==-0           | kxy4wI6PoGY6ThmVnYlqGQ==             | 320      |   |
| 20201009-1 | 2020-10-9-4CGNDA==-0           | MxBZy1S0YFb6rcmDaPU+zw==             | 306      |   |
| 20201009-1 | 2020-10-9-4CGNDA==-0           | SQeJ/bfB/e6EulF/uhgLBg==             | 300      |   |
| 20201009-1 | 2020-10-9-4CGNDA==-0           | Tyhnn+ARl71P9FcfKetokA==             | 300      |   |
| 20201009-1 | 2020-10-9-4CGNDA==-0           | Xc5Ju04GzKJUIIXyErPXwg==             | 300      |   |
| 20201009-1 | 2020-10-9-4CGNDA==-0           | Xhrm5woYEwFbM08CUI85ug==             | 320      |   |

the download output of my testcase 

```
      .andExpect(mvcResult -> {
        EfgsProto.DiagnosisKeyBatch response = EfgsProto.DiagnosisKeyBatch.parseFrom(
          mvcResult.getResponse().getContentAsByteArray());

        Assert.assertEquals(4000, response.getKeysCount());
        MutableInt cnt = new MutableInt(0);
        response.getKeysList().forEach(key -> {
          cnt.increment();
          System.out.println("Key:" + cnt);
          System.out.println("DaysSinceOnsetOfSymptoms:" + key.getDaysSinceOnsetOfSymptoms());
        });
      });
```
can be viewed here:

[downloadeTestKeys.txt](https://github.com/eu-federation-gateway-service/efgs-federation-gateway/files/5358110/downloadeTestKeys.txt)


I couldn't find any missing 'payload_days_since_onset_of_symptoms'

**Comment by mschulte-tsi** [comment]
I took another look at the decoding and we don't seem to have a problem there.
I could decode all payload_days_since_onset_of_symptoms
[Debug.xlsx](https://github.com/eu-federation-gateway-service/efgs-federation-gateway/files/5359216/Debug.xlsx)
Also the amount of keys was consistent

**Comment by dfischer-tech** [comment]
short summary by Jörg:
```
short Update from today after a session between SAP, Ops and TSI team:
Issue is not fixed yet.

-	Assumption with corrupted entries in EFGS database was not valid
-	After some further investigation on Friday the problem only exist for daysSinceOnsetOfSymptoms with value = 0
-	EFGS extended the log entries
-	Rerun the test with the result that EFGS delivers all entries including value = 0
-	In CWA server possible issue code line was found 
-	Could not fixed instantly – Evgenii gives an update today or we continue on Monday morning
```

**Comment by dfischer-tech** [comment]
Hello colleagues,
Info from Skrebtcov, Evgenii:
```
the test was successful: after default value was changed to ‘0’, all batches with DSOS = 0 were processed and the issue doesn’t appear anymore. 
I’ll proceed with the proper change request for the new image.

We will continue on Monday to understand why 
federationDiagnosisKey.hasDaysSinceOnsetOfSymptoms()
resolves to ‘false’, for DSOS = 0.
```

**Comment by alstiefel** [comment]
as per last comment issue closed
