### ISSUE TITLE
Please enable dependabot alertes to receive pull requests for outdated or vulnerable Open Source components

### ISSUE THREAD

**Issue by koehntopp** [eu-federation-gateway-service/efgs-federation-gateway#208]
https://github.com/eu-federation-gateway-service/efgs-federation-gateway/network/alerts

**Comment by daniel-eder** [comment]
Dependabot is already enabled for this repository but shows no vulnerabilities. 
Do you see any potentially vulnerable open source dependencies that _should_ be detected by Dependabot at this point?

**Comment by koehntopp** [comment]
I was following up on a known issue and only saw manually created issues but no pull requests by dependabot - would those be visible for everyone or just the security team?

**Comment by daniel-eder** [comment]
@koehntopp Thanks a lot for following up on this. As far as I know the alerts are only visible to permissioned members, however this view shows no alerts for us at this time. Automatic creation of branches and PRs, I believe would need to be configured separately, but we should get alerts if anything is amiss. Is the issue you are referring to still open? I'd like to follow up if dependapot is working as intended.

**Comment by daniel-eder** [comment]
Dependabot just created a PR https://github.com/eu-federation-gateway-service/efgs-federation-gateway/pull/210, so it seems it's working as intended. If it missed anything let me know and we'll investigate.

**Comment by koehntopp** [comment]
Awesome, thanks for checking!
