### ISSUE TITLE
Upload: Misleading error message on failed validation

### ISSUE THREAD

**Issue by EvgeniiSkrebtcov** [eu-federation-gateway-service/efgs-federation-gateway#232]
## Describe the bug

According to the code, before EFGS persists uploaded keys, it executes some validation checks. In case such validation fails, HTTP response contains an "Invalid Signature" message. This is misleading as it does not give any hints on the actual root cause.

## Expected behavior

HTTP response contains the actual reason for the failed validation.

## Steps to reproduce the issue

Upload a batch that will fail EFGS validation (e.g. will contain keys wit rolling start interval number older than 14 days)

## Technical details

N/A

## Possible Fix

N/A

## Additional context

N/A

**Comment by ascheibal** [comment]
Batches are intended to be processed completely. Extracting some is not possible, due to the signing applied to the whole batch.
