### ISSUE TITLE
Upload: if 1 key in the batch is older than 14 days, whole batch fails validation

### ISSUE THREAD

**Issue by EvgeniiSkrebtcov** [eu-federation-gateway-service/efgs-federation-gateway#233]
## Describe the bug

According to the code, before EFGS persists uploaded keys, it executes some validation checks. In case such validation fails, HTTP response contains an "Invalid Signature" message. If an upload batch contains a key with a rolling start interval older that 14 days, the whole batch fails validation.

## Expected behavior

EFGS accepts valid keys from the batch. Invalid keys are ignored.

## Steps to reproduce the issue

Upload a batch that will contain keys wit rolling start interval number older than 14 days

## Technical details

N/A

## Possible Fix

EFGS returns a Multistatus HTTP response

## Additional context

N/A

**Comment by f11h** [comment]
Hello @EvgeniiSkrebtcov ,

this is intended behaviour. Uploading just some keys would break the signature of the uploaded batch.
