### ISSUE TITLE
Enhanced Validation of Uploaded TEKS

### ISSUE THREAD

**Issue by SchulzeStTSI** [eu-federation-gateway-service/efgs-federation-gateway#235]
## Motivation

There are some TEK rules which are currently validated recommeded by google. But there also some rules which have to be validated by the member states. 

## Additional Rules

visitedCountries: Codes must be valid regarding ISO-3166-1 , if not throw a Response "Invalid Country Code used"
AND
visitedCountries: List must not contain the Origin Value, if not throw a Response "Origin can not be part of visited Countries"

DSOS: Value MUST be between -14 and 14
OR
DSOS: Value MUST be between (n-1)86 and (n)14 ( n= x*100; x<19) 
OR
DSOS: Value MUST be between 1986 and 2014
OR
DSOS: Value MUST be between 2986 and 3014
OR
DSOS: Value MUST be between 3986 and 4014, if value not matches throw a Response "DSOS Value out of Range"

Report Type: Value MUST BE CONFIRMED_TEST, if value not matches throw a Response "Report Type not allowed."

The enhancements can be done after the commitment of eHN.

**Comment by iCesofT** [comment]
EFGS should check if valid countries as it is the server. If you don't do it, any country may send any kind of data (not only EU countries but any kind of information).
