### ISSUE TITLE
Audit Endpoint returns Audit information in wrong order

### ISSUE THREAD

**Issue by f11h** [eu-federation-gateway-service/efgs-federation-gateway#237]
## Describe the bug

Under special circumstances (they are not known yet) the audit endpoint returns the audit information in a wrong order.

Uploading 3 batches (A, B, C) with each 3 keys inside. EFGS will batch these into one batch with a batch tag (e.g. 20201029-12).
Downloading the keys will result in 9 key in the following order: A1, A2, A3, B1, B2, ...

The corresponding audit download has returned something like: 
* AuditInformation about A
* AuditInformation about C
* AuditInformation about B

This makes the Batch signature verification difficult.

## Expected behaviour

The corresponding audit download should be:
* AuditInformation about A
* AuditInformation about B
* AuditInformation about C

## Steps to reproduce the issue

not known yet

## Possible Fix

see linked PR

**Comment by cascremers** [comment]
A possible cause could be implicit concurrency in the uploads if there are multiple servers handling the requests.

(As mentioned in earlier discussions, the current ordering reconstruction based on timestamps / database result order is rather fragile especially in the context of multiple servers.)
