### ISSUE TITLE
Using audit endpoint

### ISSUE THREAD

**Issue by TomaszMolenda** [eu-federation-gateway-service/efgs-federation-gateway#241]
I have a problem with using endpoint /diagnosiskeys/audit/download/{date}/{batchTag}.

If some country uploads two set of keys in the same moment, this keys will be pushed to one batch tag. Afert that I download this batch I call audit endpoint and it serves me two autdits for the same country with different other data.

How I can validate downloaded EfgsProto.DiagnosisKeyBatch with downloaded AuditEntry?

You provided [example code](https://github.com/eu-federation-gateway-service/efgs-simulator/blob/master/src/main/java/eu/interop/federationgateway/batchsigning/BatchSignatureVerifier.java) to using but this algorithm can't work with multiple audits from from the same country.

**Comment by SchulzeS** [comment]
To validate the audits correctly, you have to use the amount in the audit response. You can find an example here: 

https://github.com/SchulzeS/efgs-federation-gateway/blob/feat/extendedauditingtest/src/test/java/eu/interop/federationgateway/auditing/BatchAuditor.java

This calculates the signature out of the given diagnosiskeys and compares it to the audit entries. This works also for multiple entries of the same country.

**Comment by f11h** [comment]
@TomaszMolenda do you have any further questions or can we close this issue?

**Comment by TomaszMolenda** [comment]
> @TomaszMolenda do you have any further questions or can we close this issue?

You can close it
