### ISSUE TITLE
Review handling of batch tag names

### ISSUE THREAD

**Issue by alstiefel** [eu-federation-gateway-service/efgs-federation-gateway#31]
Input from external
"The upload controller code has an explicit check that the uploader-chosen batchTag is not yet in the current key list, and there is a test case that effectively checks this. 
However, in practice, old keys should get deleted, and batchDocuments overwrites the batchTags of the keys. 
This means that if either a delete or batchDocuments happens between the two upload attempts, a duplicate upload will be allowed. "

The upload batch tag name must be preserved, otherwise it becomes useless. The batching should use a separate attribute for its name.

**Comment by f11h** [comment]
We have two columns containning batch tags: uploader batch tag and the batch tag which will be set by batch daemon.

So we don't see an issue in getting dublicated batches because the upload batch tag wont be changed.
