### ISSUE TITLE
Log Format Adjustment

### ISSUE THREAD

**Issue by MartinKonrad** [eu-federation-gateway-service/efgs-federation-gateway#39]
Bitte Prüfen und ggf. anpassen bzw. kommentieren. Anpassen bitte nur, wenn es nicht mit der Log best practice kollidiert, die wir seitens DIGIT genannt bekommen haben.

Here are some questions from my side:
-	According to the document we received from you, log message “error verifying batch signature”, which is not in the sample logs, comes with “exception”. Can it be ensured that “exception” is one-line rather than multi-line? Meaning, we hope that ‘\n’ or any new line character can be replaced by other characters.
-	The following lines (in line 195) seems to be one log which contains multiple lines:

timestamp=2020-08-14T09:17:08.577Z, level=ERROR, hostname=BE1DA651, pid=19900, trace=e1d9197707c04061, span=e1d9197707c04061, thread=http-nio-8090-exec-3, class=o.h.engine.jdbc.spi.SqlExceptionHelper, message="Eindeutiger Index oder Primärschlüssel verletzt: "PUBLIC.CONSTRAINT_INDEX_3 ON PUBLIC.DIAGNOSISKEY(PAYLOAD_HASH) VALUES 9"
Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_3 ON PUBLIC.DIAGNOSISKEY(PAYLOAD_HASH) VALUES 9"; SQL statement:
insert into diagnosiskey (id, batch_tag, created_at, format_major_version, format_minor_version, payload_days_since_onset_of_symptoms, payload_key_data, payload_origin, payload_report_type, payload_rolling_period, payload_rolling_start_interval_number, payload_transmission_risk_level, payload_visited_countries, payload_hash, uploader_information_batch_signature, uploader_information_batch_tag, uploader_information_country, uploader_information_thumbprint) values (null, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-200]"

Again, can ‘\n’ or any new line character be replaced by other characters? Moreover, there are “"”s inside “message”. Would it be possible to replace all the “"” inside with ‘'’ so that it won’t be ambiguous to see something like this: message="A says:"Hi. :)"".

Viele Grüße
Chun-Te Sung

**Comment by f11h** [comment]
Exceptions/Raw Stack Trace will be written in one line as 
```
exception="stacktracecontent"
```

Also I've added something to replace all newlines from the message field.

the occurence of "mid-quoation-marks" is a little bit tricky because we are adding additional logging information just with string concatenation and therefore we need a ".

We will find a solution :)

**Comment by f11h** [comment]
We will change our "additional log attributes" feature to use MDC.
