### ISSUE TITLE
Build Docker Image - Developing testing

### ISSUE THREAD

**Issue by immuniteam** [eu-federation-gateway-service/efgs-federation-gateway#47]
Hi,
Could you please argue a bit more the "docker build" part?
According to the documentation, we read "just enable the maven profile docker", what is meant? What do we have to change in the pom.xml?
Also with the command "mvn clean install" under the target folder no docker folder is created.
waiting for your kind reply!

Thank you

**Comment by daniel-eder** [comment]
Hi @immuniteam, our developers will review your request and clarify the documentation. Please give us some time to properly address this. Thank you!

**Comment by immuniteam** [comment]
no worries @daniel-eder, thanks for your fast response! 👍

**Comment by f11h** [comment]
Hi @immuniteam ,

there are several ways to activate maven profiles. The easiest approach would be to activate the docker profile when you issue you command. So to build the docker directory just execute 
```
mvn clean install -P docker
```

I will add this hint to the documentation.

**Comment by immuniteam** [comment]
thanks @f11h 
with the command  `mvn clean install -P docker
` the Docker folder is created. 
As you suggested, could be useful to add this hint to the documentation.
Thanks 👍

**Comment by f11h** [comment]
I've created a PR for the change (#56)
This issue will be closed when this PR is merged.
