### ISSUE TITLE
Swagger dosen't work. Only default swagger template is visible.

### ISSUE THREAD

**Issue by flamaniac** [eu-federation-gateway-service/efgs-federation-gateway#57]
## Describe the bug

Swagger is not available on 8090 port. There is swagger on http://localhost:**8080**/swagger-ui/index.html but it is default tamplate - with pets endpoint :) I am on the master branch.

## Expected behaviour

http://localhost:8090/swagger-ui/index.html will present api documentation

## Steps to reproduce the issue

Go to http://localhost:8090/swagger-ui/index.html - doesn't work
go to http://localhost:8080/swagger-ui/index.html - default swagger template is showing

**Comment by flamaniac** [comment]
To make it work you need to enter url: localhost:8080/swagger and will be redirected to http://localhost:8080/swagger-ui/index.html?configUrl=/api/docs/swagger-config

Documentation update will be nice.

**Comment by daniel-eder** [comment]
Thank you @flamaniac for the correct URL!
