### ISSUE TITLE
Generate onboarding documents for participating countries

### ISSUE THREAD

**Issue by mlaue-tech** [eu-federation-gateway-service/efgs-federation-gateway#7]
- [x]  needed infrastructure
- [x]  examples

- hashwert-calculation (Luis mit Bsp)
- welche Zertifikate brauchen wir, wo bekommen wir die?
- Wie funktioniert Datentopfbildung (nach Ländern werden die Töpfe gebaut...)
- Welches Datenformat? Version 1.0 hoch, dann 1.0 runter

**Comment by alstiefel** [comment]
done
