### ISSUE TITLE
`outkey` argument in `Example self signed certificate that complies with above specification`

### ISSUE THREAD

**Issue by matishadow** [eu-federation-gateway-service/efgs-federation-gateway#72]
* Source File: docs/software-design-federation-gateway-service.md
* Line(s): 585
* Question: Shouldn't instead of `outkey` argument to `openssl` should be `keyout`?

**Comment by f11h** [comment]
Yes, this is right - Can you please provide a PR for that?

**Comment by matishadow** [comment]
Thank you for the confirmation! 
I will provide a PR tomorrow.

**Comment by f11h** [comment]
Thanks for you contribution. I will close this issue now.
