### ISSUE TITLE
Setup Development Environment

### ISSUE THREAD

**Issue by mlaue-tech** [eu-federation-gateway-service/efgs-federation-gateway#8]
We need to setup the dev envirnmont in the provided DEV/OTC infrastructure

- [x]  Tennant
- [x]  Managed Server Tomcat
- [x]  Managed Server MySQL 5.6
- [ ]  Loadbalancer
- [x]  Server certificates
- [x]  DNS name
- [x] Managed Server MySQL 5.7 (Upgrade)

**Comment by f11h** [comment]
The loadbalancer not not properly configured. The Thumbprint of the mTLS certificate is not added to forwarded request.

**Comment by paszimme** [comment]
loadbalancer: benötigt config wie im Architekturdokument beschrieben. Liegt bei OTC
MySQL 5.7: benötigt Portfreischaltung. Liegt bei OTC

**Comment by alstiefel** [comment]
LoadBalancer is not finished since the last update, I propose to fix it within the next 7 days or give up on the issue

**Comment by alstiefel** [comment]
Closing because of nobody cares
