### ISSUE TITLE
Integrate Environment information to log messages

### ISSUE THREAD

**Issue by f11h** [eu-federation-gateway-service/efgs-federation-gateway#85]
## Current Implementation

Each log message contains the hostname of the worker node. Ops team also need the name of the environment (e.g. PROD, TEST, ...)

## Suggested Enhancement

Add environments name to each log message

```
timestamp="2020...", host="hostabc", env="PROD"
```

**At the moment we do not know the name of the environment variable, so this issue is on hold**

**Comment by alstiefel** [comment]
Wont fix, due to low priority.
