### ISSUE TITLE
Architecture document totally out of date

### ISSUE THREAD

**Issue by ryanbnl** [eu-federation-gateway-service/efgs-federation-gateway#87]
The architecture document which is linked in the docs:

https://ec.europa.eu/health/sites/health/files/ehealth/docs/mobileapps_interoperabilitydetailedelements_en.pdf

Contains out of date information. Specifically a whole discussion over databases with the result being to use MongoDb.

In this repository I see use of MySQL (which seems better, you at least avoid the well documented problems with the vendor behind MongoDB).

Is it possible to include that document here; and keep it up to date? Preferably in markdown.

**Comment by ascheibal** [comment]
Hi @ryanbnl, thank you for that hint. You will find the most current information about the technical part of the project in this repo, as we feel this is the first place to look for such things.
We may ask the EU, who is the official owner of this document to publish a copy here.

**Comment by daniel-eder** [comment]
We just got confirmation that the updated document has been approved by the EU, will be published on their website in the near future. Once the updated document is available in the official channel we will update the links in our documentation.

Thank you again for notifying us!

**Comment by ryanbnl** [comment]
Thanks!

**Comment by daniel-eder** [comment]
#99 adds the link to the latest approved document. Please reopen this issue if anything remains unclear or you see any further discrepancies.
