### ISSUE TITLE
Publish docker image in GitHub docker registry

### ISSUE THREAD

**Issue by ebeigarts** [eu-federation-gateway-service/efgs-federation-gateway#89]
It would be nice that docker images would be published on GitHub Packages, so backend developers wouldn't need to install Java, etc to be able to test integration with EFGS on local dev machine.

Currently to build docker images on a Mac you have to:

```bash
brew tap AdoptOpenJDK/openjdk
brew cask install adoptopenjdk11
export JAVA_HOME=$(/usr/libexec/java_home -v11)
mvn clean install -P docker
bash -c "cd target/docker && docker-compose up --build"
```

It would be much easier to just:

```bash
# docker pull docker.pkg.github.com/eu-federation-gateway-service/efgs-federation-gateway/backend:latest
docker-compose up --build
```

I could try to make a PR with GitHub Action workflow changes if this is something you are interested.

Also currently as I understand that without F5 LB there is no way to start EFGS with mTLS locally on developer machine. I have created some k8s configs with envoy proxy (the only one I could find that supports client cert sha256 fingerprints in headers) and it looks like it could be ok for dev/test environment for us - https://gist.github.com/ebeigarts/e129f7bd44ef06fbbb5ce028af8c9cdf

**Comment by daniel-eder** [comment]
@ebeigarts Thank you for the suggestion and the offer to create a PR. Our devs will review this, please give us some time to get back to you.

**Comment by daniel-eder** [comment]
@ebeigarts May I ask you to create the PR? Our developers will review your specific suggestions and provide feedback. Thank you!
